name: Deploy Image to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push-whisper-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v5

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push with version tag
        run: |
          VERSION=${{ github.ref_name }}

          docker build . --tag ghcr.io/${{ github.repository_owner }}/whisper:${VERSION}
          docker build . --tag ghcr.io/${{ github.repository_owner }}/whisper:latest
          docker push ghcr.io/${{ github.repository_owner }}/whisper:${VERSION}
          docker push ghcr.io/${{ github.repository_owner }}/whisper:latest

  deploy:
    needs: push-whisper-image
    runs-on: [self-hosted]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: nckslvrmn/docker-compose-deploy@main
        with:
          file: compose.yml
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}
          WHISPER_VERSION: ${{ github.ref_name }}
