name: Deploy Image to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push-whisper-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v5

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push with version tag
        run: |
          VERSION=${{ github.ref_name }}

          docker build . --tag ghcr.io/${{ github.repository_owner }}/whisper:${VERSION}
          docker build . --tag ghcr.io/${{ github.repository_owner }}/whisper:latest
          docker push ghcr.io/${{ github.repository_owner }}/whisper:${VERSION}
          docker push ghcr.io/${{ github.repository_owner }}/whisper:latest
