name: Deploy To Home 

jobs:
  deploy:
    needs: push-whisper-image
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4
      - uses: nckslvrmn/docker-compose-deploy@main
        with:
          file: compose.yml
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DYNAMO_TABLE: ${{ secrets.DYNAMO_TABLE }}
